name: OrangeHRM Regression Test

on:
  schedule:
    # 01:00 WIB = 18:00 UTC
    - cron: '0 18 * * *'

  workflow_dispatch:

jobs:
  regression-test:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Makassar

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Automation Test
        run: npm test
      
      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: automation-report
          path: reports/

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
        name: screenshots
        path: screenshots/